# Generated by Django 3.1.7 on 2021-03-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
