# Generated by Django 3.1.7 on 2021-03-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=200)),
                ('stationcode', models.CharField(max_length=200)),
                ('stationcity', models.CharField(max_length=200)),
                ('prevstation', models.CharField(max_length=200)),
                ('nextstation', models.CharField(max_length=200)),
            ],
        ),
    ]
