# Generated by Django 3.1.7 on 2021-03-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainname', models.CharField(max_length=200)),
                ('trainnumber', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('arrivaltime', models.TimeField()),
                ('departuretime', models.TimeField()),
                ('arrivaldate', models.DateField()),
                ('departuredate', models.DateField()),
                ('runningdays', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('trainclass', models.CharField(max_length=50)),
                ('birth', models.CharField(max_length=50)),
                ('availableseats', models.IntegerField()),
            ],
        ),
    ]
