# Generated by Django 3.1.7 on 2021-03-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_trains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trains',
            name='arrivaldate',
        ),
        migrations.RemoveField(
            model_name='trains',
            name='departuredate',
        ),
        migrations.AlterField(
            model_name='trains',
            name='arrivaltime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trains',
            name='departuretime',
            field=models.CharField(max_length=100),
        ),
    ]
