# Generated by Django 3.1.7 on 2021-03-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_auto_20210319_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='station',
            field=models.ManyToManyField(to='train.Stations'),
        ),
    ]
