# Generated by Django 3.1.7 on 2021-03-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_trains_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='train.stations'),
        ),
        migrations.AlterField(
            model_name='trains',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='train.stations'),
        ),
    ]
