# Generated by Django 3.1.7 on 2021-04-01 03:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eticket', '0003_auto_20210401_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passenger_details',
            new_name='PassengerDetail',
        ),
    ]
