# Generated by Django 3.1.7 on 2021-04-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0005_auto_20210401_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
